"""
    Problem 45:

    Problem Description:

    Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
    Triangle        T_=n(n+1)/2         1, 3, 6, 10, 15, ...
    Pentagonal      P_=n(3n-1)/2        1, 5, 12, 22, 35, ...
    Hexagonal       H_=n(2n-1)          1, 6, 15, 28, 45, ...

    It can be verified that T_85 = P_165 = H_143 = 40755.

    Find the next triangle number that is also pentagonal and hexagonal.


    Problem Solution:
    Try first 60ish thousand of each. 60,000 found by experimentation


"""
def main():
    # generate first 60,000 of each series
    tris  = set(map(lambda n: n * (n + 1) / 2,     range(286, 60000)))
    quads = set(map(lambda n: n * (3 * n - 1) / 2, range(166, 60000)))
    pents = set(map(lambda n: n * (2 * n - 1),     range(144, 60000)))

    # find smallest t contained in each
    print min(t for t in tris if t in quads and t in pents)


main()
